config/routes.rb
Rails.application.routes.draw do
  resources :questions, only: [:show, :index]
  resources :responses, only: [:show, :index]

  root to: 'creative_qualities#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creative_quality.rb
# == Schema Information
#
# Table name: creative_qualities
#
#  id          :integer          not null, primary key
#  color       :string
#  description :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class CreativeQuality < ApplicationRecord
  has_many :question_choices

  validates :name, :description, :color, presence: true

  # NOTE: unused
  def self.all_names
    all.map(&:name).uniq
  end

  def final_score
    # return @final_score ||= rand(200) - 100
    @final_score ||= clamp(
      (total_raw_for_quality.to_f / total_max_for_quality * 100).to_i,-100,
      100
    )
  end

  def total_raw_for_quality
    Response.all.sum do |res|
      res.total_raw_score(name)
    end
  end

  def total_max_for_quality
    Response.all.sum do |res|
      res.total_max_score(name)
    end
  end

  def serialize
    attributes.merge(
      "final_score" => final_score
    )
  end

  private
  def clamp(num, min, max)
    return min if num < min
    return max if num > max
    num
  end
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  position   :integer
#  title      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ApplicationRecord
  has_many :question_choices, inverse_of: :question

  validates :title, presence: true

  accepts_nested_attributes_for(:question_choices)

  def max_score(quality_name)
    question_choices
      .with_quality_name(quality_name)
      .max_by(&:score).try(:score) || 0
  end
end

app/models/question_choice.rb
# == Schema Information
#
# Table name: question_choices
#
#  id                  :integer          not null, primary key
#  score               :integer
#  text                :text
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  creative_quality_id :integer
#  question_id         :integer
#
# Indexes
#
#  index_question_choices_on_creative_quality_id  (creative_quality_id)
#  index_question_choices_on_question_id          (question_id)
#

class QuestionChoice < ApplicationRecord
  belongs_to :question, inverse_of: :question_choices
  belongs_to :creative_quality

  validates :text, :question, :creative_quality, presence: true
  validates :score, numericality: { only_integer: true }

  scope :with_quality_name, ->(quality_name) {
    joins(:creative_quality).where('creative_qualities.name = ?', quality_name)
  }

  def creative_quality_name
    @creative_quality_name ||= creative_quality.name
  end
end

app/models/question_response.rb
# == Schema Information
#
# Table name: question_responses
#
#  id                 :integer          not null, primary key
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  question_choice_id :integer
#  response_id        :integer
#
# Indexes
#
#  index_question_responses_on_question_choice_id  (question_choice_id)
#  index_question_responses_on_response_id         (response_id)
#

class QuestionResponse < ApplicationRecord
  belongs_to :question_choice
  belongs_to :response

  validates :question_choice, presence: true
  validates :response, presence: true

  delegate :question, :creative_quality, :score, to: :question_choice

  def score_by_quality_name(quality_name)
    quality_name == creative_quality.name ? score : 0
  end
end

app/models/response.rb
# == Schema Information
#
# Table name: responses
#
#  id         :integer          not null, primary key
#  first_name :string
#  last_name  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Response < ApplicationRecord
  has_many :question_responses

  validates :first_name, presence: true
  validates :last_name, presence: true

  delegate :count, to: :question_responses, prefix: true

  def display_name
    "#{first_name} #{last_name}"
  end

  def completed?
    question_responses_count == Question.count
  end

  def total_raw_score(quality_name)
    question_responses.sum do |q_res|
      q_res.score_by_quality_name(quality_name)
    end
  end

  def total_max_score(quality_name)
    question_responses.sum do |q_res|
      q_res.question.max_score(quality_name)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/creative_qualities_controller.rb
class CreativeQualitiesController < ApplicationController
  def index
    @creative_qualities = CreativeQuality.all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def show
    @question = Question.includes(:question_choices).find(params[:id])
  end

  def index
    @questions = Question.order(:id)
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def show
    @all_creative_quality_names = CreativeQuality.all_names
    @response = Response
      .includes(question_responses: [question_choice: [question: :question_choices]])
      .find(params[:id])
  end

  def index
    @responses = Response.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/creative_qualities/index.html.erb
<script>
  /*
    Quick way to get creativeQualities to JS.
    Would eventually be replaced with API call.
  */
  window.qualsJSON = <%==
    @creative_qualities.map(&:serialize).to_json
  %>
</script>

<!-- This is where the React app gets rendered -->
<div id="react-root">
  <!-- currently just rendering H2 title -->
</div>

app/views/layouts/_footer.html.erb
<div style="padding: 100px 0;">
  <hr>

  <small class="text-muted">
    Thoughtfully designed by IDEO in California.
  </small>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Creative Difference', root_path, class: 'navbar-brand' %>
    </div>

    <div class="navbar-collapse collapse">
      <ul class="navbar-nav nav">
        <li>
          <%= link_to 'Questions', questions_path %>
        </li>

        <li>
          <%= link_to 'Responses', responses_path %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_notifications.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Creative Difference – IDEO</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/notifications' %>

    <div class="container">

      <div id="react-root"></div>

      <div ng-app="c-delta">
        <%= yield %>
      </div>

      <%= render 'layouts/footer' %>
    </div>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/questions/_header.html.erb
<h3>
  <div>
    <strong>
      <%= "Question #{question.id}" %>
    </strong>
  </div>

  <%= question.title %>
</h3>

app/views/questions/index.html.erb
<div class="row">
  <div class="col-md-8">
    <h2>
      Questions
    </h2>

    <table class="table">
      <tbody>
        <% @questions.find_each do |question| %>
          <tr>
            <td>
              <strong>
                <%= question.id %>.
              </strong>
            </td>

            <td>
              <%= truncate(question.title, length: 75) %>
            </td>

            <td>
              <%= link_to 'View', question_path(question), class: 'btn btn-default btn-xs' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/questions/show.html.erb
<div class="row">
  <div class="col-md-7">
    <%= render 'questions/header', question: @question %>

    <hr>

    <h3>
      Choices
    </h3>

    <%= bootstrap_form_for(@question) do |question_form| %>
      <table class="table">
        <% @question.question_choices.each_with_index do |question_choice, index| %>
          <% hide_label = index > 0 %>

          <%= question_form.fields_for(:question_choices, question_choice) do |choice_fields| %>
            <tr>
              <td>
                <%= choice_fields.text_field :text, readonly: true, hide_label: hide_label %>
              </td>

              <td>
                <%= choice_fields.select :creative_quality_id, options_for_select(CreativeQuality.pluck(:name, :id)), { hide_label: hide_label }, { disabled: true } %>
              </td>

              <td>
                <%= choice_fields.text_field :score, readonly: true, hide_label: hide_label %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </table>

      <div class="text-right">
        <%= question_form.submit 'Update Choices', disabled: true %>
      </div>
    <% end %>
  </div>
</div>

app/views/responses/index.html.erb
<div class="row">
  <div class="col-md-8">
    <h2>
      Responses
    </h2>

    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Completed?</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @responses.find_each do |response| %>
          <tr>
            <td>
              <%= truncate(response.display_name, length: 90) %>
            </td>

            <td>
              <% if response.completed? %>
                Yes
              <% else %>
                <span class="text-danger">No</span>
              <% end %>
            </td>

            <td>
              <%= link_to 'View', response_path(response), class: 'btn btn-default btn-xs' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/responses/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>
          <%= @response.display_name %>
        </h3>
      </div>

      <div class="panel-body">
        Completed
        <%= @response.question_responses_count %>
        of
        <%= Question.count %>
        questions
        <hr/>

        <div>
          <b>Purpose</b>
          <ul>
            <li>Raw score <%= @response.total_raw_score('Purpose') %></li>
            <li>Max score <%= @response.total_max_score('Purpose') %></li>
          </ul>
        </div>
        <div>
          <b>Empowerment</b>
          <ul>
            <li>Raw score <%= @response.total_raw_score('Empowerment') %></li>
            <li>Max score <%= @response.total_max_score('Empowerment') %></li>
          </ul>
        </div>
        <div>
          <b>Collaboration</b>
          <ul>
            <li>Raw score <%= @response.total_raw_score('Collaboration') %></li>
            <li>Max score <%= @response.total_max_score('Collaboration') %></li>
          </ul>
        </div>
      </div>
    </div>

    <hr>

    <% @response.question_responses.each do |question_response| %>
      <%= render 'questions/header', question: question_response.question %>

      <table class="table table-bordered">
        <% question_response.question.question_choices.each do |question_choice| %>
          <tr>
            <td>
              <% if question_choice == question_response.question_choice %>
                <strong>
                  <%= question_choice.text %>
                  <div class="color-<%= question_choice.score > 0 ? 'green' : 'red' %>">
                    <%= question_choice.creative_quality_name %> <%= question_choice.score %>
                  </div>
                </strong>
              <% else %>
                <span class="text-muted">
                  <%= question_choice.text %>
                </span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</div>